environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: npm install -g npm@latest
  - ps: npm install

test_script:
    - npm run test:appveyor

build: off